name: Build LLVM for windows x64

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        token: ${{secrets.PAT}}
        submodules: 'recursive'

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5
      with:
        version: "1.12.1"

    - name: Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -G Ninja -S ${{github.workspace}}/llvm -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS=clang;lld -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/build/llvm_install" -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_RUNTIMES=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_OBFUSCATION_LINK_INTO_TOOLS=ON

    - name: Build
      # Build your program with the given configuration
      run: |
        cd ${{github.workspace}}/build
        ninja
        ninja install

    - name: Zip LLVM
      run: |
        7z a -y llvm_obf_Win64.zip ./llvm_install/*
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: llvm_obf_Win64.zip
        path: ${{github.workspace}}/build/llvm_obf_Win64.zip
